name: Docker Image CI

on: [pull_request]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Stop MySql
        run: sudo service mysql stop
      - name: Run docker-compose
        run: docker-compose up -d
      - name: Composer install
        run: docker-compose exec -w /code/test-app php "composer install"
      - name: Test App
        run: |
          if ! curl http://localhost:8080 | grep -q 'Hello World!'; then
            echo "App healthcheck failed"
          fi
