name: Docker Image CI

on: [pull_request]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Stop MySql
        run: sudo service mysql stop
      - name: Run docker-compose
        run: docker-compose up -d
      - name: Composer install
        run: docker-compose exec -T php composer install -d /code/test-app
      - name: Containers status
        run: docker-compose ps && docker-compose logs mysql
      - name: Test App
        run: curl -s http://localhost:8080
