name: Docker Image CI

on: [pull_request]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Stop MySql
      run: sudo service mysql stop

    - name: Execute docker-compose file
      run: docker-compose up -d
