name: Docker Image CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Stop MySql
        run: sudo service mysql stop
      - name: Elastic prepare data dir
        run: |
          mkdir -R ./var/elasticsearch/data
          chmod g+rwx ./var/elasticsearch/data
          chgrp 1000 ./var/elasticsearch/data
      - name: Run docker-compose
        run: docker-compose up -d
      - name: Composer install
        run: docker-compose exec -T php composer install -d /code/test-app
      - name: Wait
        run: sleep 15
      - name: Elastic
        run: docker-compose logs elasticsearch
      - name: Test App
        run: |
          if ! curl -s http://localhost:8080 | grep -q 'Hello World!'; then
            exit 1
          fi
